# Generated by Django 4.0.4 on 2022-04-12 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice_project', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
