# Generated by Django 4.0.4 on 2022-04-12 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice_project', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empodel',
            new_name='Usermodel',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='empname',
            new_name='first_name',
        ),
    ]
