# Generated by Django 4.0.4 on 2022-04-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_project', '0004_rename_empodel_usermodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='first_name',
            field=models.TextField(max_length=500),
        ),
    ]
