# Generated by Django 4.0.4 on 2022-04-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_project', '0010_alter_usermodel_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='email',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='gender',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='ip_address',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='last_name',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
